# Generated by Django 3.1.6 on 2021-02-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210211_1510'),
        ('_class', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentClass',
            new_name='Class',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
