# Generated by Django 3.1.7 on 2021-03-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_class', '0002_auto_20210211_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(to='_class.Class'),
        ),
    ]
