# Generated by Django 3.2.1 on 2021-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('link', models.CharField(max_length=400, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
