# Generated by Django 3.1.7 on 2021-03-01 02:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_class', '0003_subject_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('week', models.CharField(help_text='lecture week', max_length=2)),
                ('timestamp', models.DateField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_class.class')),
            ],
        ),
    ]
