# Generated by Django 3.1.7 on 2021-04-02 12:09

from django.db import migrations, models
import lecture.validator


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20210402_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='note',
            field=models.FileField(default='lecture.pdf', upload_to='lecture notes', validators=[lecture.validator.validate_file_extension]),
        ),
    ]
