# Generated by Django 3.1.7 on 2021-04-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20210402_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='week',
        ),
    ]
