# Generated by Django 3.2.4 on 2021-06-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_remove_lecture_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('link', models.CharField(max_length=400, unique=True)),
                ('poster', models.ImageField(default='course.jpg', upload_to='course_posters')),
            ],
        ),
    ]
