# Generated by Django 3.2 on 2021-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=400)),
                ('message', models.TextField()),
                ('recipient', models.CharField(choices=[('students', 'students'), ('teachers', 'teachers')], max_length=9)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
