# Generated by Django 3.1.7 on 2021-04-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.class'),
        ),
        migrations.AddField(
            model_name='video',
            name='term',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], default=(1, 1), max_length=3),
        ),
    ]
