# Generated by Django 3.1.7 on 2021-04-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('video', '0002_auto_20210403_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='level',
        ),
        migrations.AddField(
            model_name='video',
            name='level',
            field=models.ManyToManyField(to='classroom.Class'),
        ),
        migrations.AlterField(
            model_name='video',
            name='term',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=('1', '1'), max_length=3),
        ),
    ]
