# Generated by Django 3.2 on 2021-04-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('video', '0003_auto_20210404_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='level',
        ),
        migrations.AddField(
            model_name='video',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.class'),
        ),
    ]
