# Generated by Django 3.1.7 on 2021-04-02 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.subject')),
            ],
        ),
        migrations.CreateModel(
            name='MockTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
                ('a', models.CharField(default='', max_length=400)),
                ('b', models.CharField(default='', max_length=400)),
                ('c', models.CharField(default='', max_length=400)),
                ('d', models.CharField(default='', max_length=400)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_test.mocktest')),
            ],
        ),
    ]
