# Generated by Django 3.1.7 on 2021-04-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_test', '0002_mocktestquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='title',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
