# Generated by Django 3.2 on 2021-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_test', '0004_mocktestquestion_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestquestion',
            name='timer',
            field=models.CharField(choices=[('30', '30'), ('45', '45'), ('60', '60')], default=('30', '30'), max_length=2),
        ),
    ]
