# Generated by Django 3.2 on 2021-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_test', '0007_auto_20210417_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktestquestion',
            name='question',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
