# Generated by Django 3.1.7 on 2021-03-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210211_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default='', help_text='Enter referral phone number', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_referral_code',
            field=models.CharField(default='', help_text='Enter referral phone number', max_length=20, unique=True),
        ),
    ]
