# Generated by Django 3.1.7 on 2021-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210301_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default='', help_text='Enter referral phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_referral_code',
            field=models.CharField(default='', help_text='Enter referral phone number', max_length=20),
        ),
    ]
