# Generated by Django 3.2 on 2021-04-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.png', null=True, upload_to='profile_images %Y/%M/%d'),
        ),
    ]
