# Generated by Django 3.1.7 on 2021-03-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210301_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='syllable',
            field=models.CharField(choices=[('E.Africa', 'Learner conner E.Africa'), ('W.Africa', 'Learner conner W.Africa')], default='', max_length=25),
        ),
    ]
