# Generated by Django 3.2.4 on 2021-07-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coupon',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
