# Generated by Django 3.2 on 2021-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
