# Generated by Django 3.2.1 on 2021-06-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_coupons_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
