# Generated by Django 3.2.1 on 2021-06-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20210407_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='date_time',
            new_name='subscription_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
