# Generated by Django 3.2.1 on 2021-06-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20210607_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
